<a href="https://colab.research.google.com/github/codewithswatiee/DS-AI-ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

In [20]:
### creating arrays in numpy

## 1d array:
arr1 = np.array([1, 2, 3 ,4 ,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [21]:
arr2 = np.array([1, 2, 3, 4 , 5])
arr2.reshape(1, 5) # 1 row 5 elements

array([[1, 2, 3, 4, 5]])

In [22]:
#2d array

arr2 = np.array([[1, 2, 3, 4, 5], [1,2, 3, 4, 5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [23]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [24]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
##Atributes in np.array

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array: ",arr)
print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Sata Type: ",arr.dtype)
print("Size (no. of elements): ",arr.size)
print("Item size(in bytes): ",arr.itemsize)

Array:  [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Dimension:  2
Sata Type:  int64
Size (no. of elements):  6
Item size(in bytes):  8


In [31]:
##Numpy Vectorized Operations:

arr1 = np.array([1, 2, 4, 5, 6])
arr2 = np.array([10, 20, 30, 40, 50])

#Element vise addition:
print("Addition: ", arr1 + arr2)


##Element wise Substraction
print("Substraction: ", arr1-arr2)

##Element wise Multiplication
print("Multiplication: ", arr1*arr2)


##Element wise Division
print("Division: ", arr2/arr1)

Addition:  [11 22 34 45 56]
Substraction:  [ -9 -18 -26 -35 -44]
Multiplication:  [ 10  40 120 200 300]
Division:  [10.         10.          7.5         8.          8.33333333]


In [32]:
## Universal Functions
arr = np.array([2, 3, 5, 6,7])

##square root
print(np.sqrt(arr))

##Exponential
print(np.exp(arr))

##Sine
print(np.sin(arr))

## Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.23606798 2.44948974 2.64575131]
[   7.3890561    20.08553692  148.4131591   403.42879349 1096.63315843]
[ 0.90929743  0.14112001 -0.95892427 -0.2794155   0.6569866 ]
[0.69314718 1.09861229 1.60943791 1.79175947 1.94591015]


In [33]:
## Slicing and indexing

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 2, 3,4, 5]])
print(arr)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [34]:
arr[0][0]

np.int64(1)

In [40]:
print(arr[1:, 2:])
print(arr[:2, 2:])

[[ 8  9 10]
 [ 3  4  5]]
[[ 3  4  5]
 [ 8  9 10]]


In [42]:
## Modify array element
arr[0,0] = 100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [  1   2   3   4   5]]


In [44]:
arr[1:] = 3
print(arr)

[[100   2   3   4   5]
 [  3   3   3   3   3]
 [  3   3   3   3   3]]


In [45]:
### Statistical concepts -- Normalization
## to have a mean of 0 and std of 1

data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
stdev = np.std(data)

normalized_data = (data-mean)/stdev
print("Normalized data: ",normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
### Statistical concepts -- Mean, median, variance, std:

print("Mean: ",np.mean(data))
print("Median: ", np.median(data))
print("Variance: ", np.var(data))
print("Standard deviation: ", np.std(data))

Mean:  3.0
Median:  3.0
Variance:  2.0
Standard deviation:  1.4142135623730951


In [50]:
## Logical Operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 7, 8, 9, 10])
data[data>5]


array([ 6,  7,  7,  8,  9, 10])

In [51]:
data[(data >=5) & (data<=9)]

array([5, 6, 7, 7, 8, 9])